[env]
platform = ststm32
board = nucleo_l476rg
framework = arduino
monitor_speed = 115200

; --- UMGEBUNG FÜR SPI TEST ---
[env:test_spi]
build_src_filter = +<*> -<main.cpp> +<tests/spi_check.cpp>

; --- UMGEBUNG FÜR I2C TEST ---
[env:test_i2c]
build_src_filter = +<*> -<main.cpp> +<tests/i2c_scan.cpp>

; --- UMGEBUNG FÜR DAS HAUPTPROGRAMM (Ping-Pong) ---
[env:main_app]
build_src_filter = +<*> -<tests/>