; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = nucleo_l476rg
framework = arduino
lib_deps = 
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	jgromes/RadioLib@^7.6.0

[env:lora_sender]
build_src_filter = -<*> +<sender_main.cpp>
upload_port = /dev/cu.usbmodem11403
monitor_port = /dev/cu.usbmodem11403
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BMP280 Library@^3.0.0
	jgromes/RadioLib@^7.6.0

[env:lora_empfaenger]
build_src_filter = -<*> +<empfaenger_main.cpp>
upload_port = /dev/cu.usbmodem11303
monitor_port = /dev/cu.usbmodem11303
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit BMP280 Library@^3.0.0
	jgromes/RadioLib@^7.6.0
